#!/usr/bin/env python2
import time
from math import pi

from service_router import *
from kinematics     import Kinematics
######
K = Kinematics()

ee_xyz, servoPos = K.doFkine(all_positions)
print(ee_xyz)